directory:
  autoencoder:
    base: XXX
    test: XXX
    train: XXX
    valid: XXX
  collections: XXX
models:
  simple:
    batch_size: XXX
    callbacks:
      checkpoint:
        directory: XXX
        period: XXX
        verbose: XXX
      csv_logger:
        append: XXX
        directory: XXX
      display_picture:
        epoch_laps: XXX
    epochs: XXX
    initial_epoch: XXX
    input_channel: XXX
    input_height: XXX
    input_width: XXX
    learning_rate: XXX
    model_name: XXX
    save_directory: XXX
    steps_per_epoch: XXX
    use_multiprocessing: XXX
    validation_freq: XXX
    validation_steps: XXX
    verbose: XXX
    workers: XXX
mysql:
  database:
    name: XXX
    password: XXX
    port: XXX
    server: XXX
    user: XXX
training:
  proportions:
    test: XXX
    train: XXX
    valid: XXX
  seed: XXX
version: XXX
